Implement basic functionality
cursorinsight/Dumper.jl pull request #2
Opened 2022-06-20 13:44 UTC by tortelio

2022-06-24 14:44 UTC, dhanak requested changes
Generally okay, with some glitches.

2022-06-24 14:44 UTC, dhanak commented on src/Dumper.jl
> +    end |> esc
It is generally not recommended to escape entire expressions, escape individual interpolations instead.

The added benefit, for example, is that you don't have to interpolate `save`.

2022-06-24 14:46 UTC, dhanak commented on src/Dumper.jl
> +            let _path = $isabsolute ? $path : joinpath($directory, $path)
Something along these lines:

```
return if STATE.enabled
    path = isabsolute ? path : joinpath(directory, path)
    :( save($path, $mime, $(esc(variable)), $mode) )
else
    :nothing
end
```

2022-06-30 13:36 UTC, tortelio commented on src/Dumper.jl
> +            let _path = $isabsolute ? $path : joinpath($directory, $path)
You are kind of right, but I was intentionally made this "dynamic". If you want to switch on-the-fly than you have to implement like this.

2022-06-30 13:40 UTC, tortelio commented on src/Dumper.jl
> +    save(io, MIME"text/plain", x)
You are right.

2022-06-30 13:41 UTC, tortelio commented on src/Dumper.jl
> +    mime::MIME = MIME"text/plain"()
You are right.

2022-06-30 13:42 UTC, tortelio commented on src/Utilities.jl
> +    return joinpath(path, "dump-" * format(now(), "YYYYmmdd-HHMMSS"))
Fine.

2022-07-11 10:09 UTC, dhanak commented on src/Dumper.jl
> +            let _path = $isabsolute ? $path : joinpath($directory, $path)
Ok, I see what you mean. I still don't like this macro implementation, it seems too convoluted, and now it calls the `STATE()` function too many times, just to force dynamic behavior.

I'm thinking the following now: put most part of the dump macro body in a function.

```jl
function dump(name, value;
              isabsolute::Bool = STATE().isabsolute,
              directory::AbstractString = STATE().directory,
              path::AbstractString = name,
              [etc.])
   STATE().enabled || return
   path = isabsolute ? path : joinpath(directory, path)
   save(path, mime, variable; mode)
end
                 
And then just call this function from the macro after the dict conversion.

2022-07-25 13:39 UTC, tortelio commented on src/Dumper.jl
> +            let _path = $isabsolute ? $path : joinpath($directory, $path)
Finally, we couldn't find the straight-forward best solution.

2022-08-04 08:58 UTC, merged